"use client";

import Link from "next/link";
import Image from "next/image";
import { ArrowLeft, ArrowRight, Minus, Plus, ShoppingBag, Trash2 } from "lucide-react";
import { useCart } from "@/components/cart-provider";
import { formatPrice } from "@/lib/format";

export function CartPage() {
  const { items, subtotalCents, updateQuantity, removeItem } = useCart();
  const shippingCents = subtotalCents >= 7500 ? 0 : 850;
  if (!items.length) return <main className="cart-page site-shell"><Link className="back-link" href="/shop"><ArrowLeft size={15} /> Keep shopping</Link><div className="cart-page__empty"><ShoppingBag size={32} strokeWidth={1.2} /><p className="eyebrow">Your HUSHWORK bag</p><h1>Nothing here<br /><em>yet.</em></h1><p>Start with something useful for the hours after.</p><Link className="button button--dark" href="/shop">Browse the shelf <ArrowRight size={16} /></Link></div></main>;
  return <main className="cart-page site-shell"><Link className="back-link" href="/shop"><ArrowLeft size={15} /> Keep shopping</Link><div className="cart-page__heading"><div><p className="eyebrow">Your HUSHWORK bag</p><h1>Bring the good<br /><em>things home.</em></h1></div><span>{items.length} {items.length === 1 ? "object" : "objects"}</span></div><div className="cart-page__grid"><section className="cart-page__items" aria-label="Bag items">{items.map((item) => <article className="cart-page__item" key={item.slug}><div className="cart-page__image">{item.imageUrl && <Image src={item.imageUrl} alt={item.name} fill sizes="(max-width: 700px) 32vw, 180px" />}</div><div className="cart-page__item-copy"><div><p className="eyebrow">{item.visual}</p><h2>{item.name}</h2><p>{formatPrice(item.priceCents)}</p></div><div className="cart-page__item-actions"><div className="quantity-control"><button type="button" onClick={() => item.quantity === 1 ? removeItem(item.slug) : updateQuantity(item.slug, item.quantity - 1)} aria-label={`Decrease ${item.name} quantity`}><Minus size={14} /></button><span>{item.quantity}</span><button type="button" onClick={() => updateQuantity(item.slug, item.quantity + 1)} disabled={item.quantity >= item.stock} aria-label={`Increase ${item.name} quantity`}><Plus size={14} /></button></div><button className="text-button" type="button" onClick={() => removeItem(item.slug)}><Trash2 size={14} /> Remove</button></div></div><strong>{formatPrice(item.priceCents * item.quantity)}</strong></article>)}</section><aside className="cart-page__summary"><p className="eyebrow">Order summary</p><div><span>Subtotal</span><strong>{formatPrice(subtotalCents)}</strong></div><div><span>Delivery</span><strong>{shippingCents ? formatPrice(shippingCents) : "Free"}</strong></div><small>{shippingCents ? `Add ${formatPrice(7500 - subtotalCents)} for free delivery.` : "You have unlocked free delivery."}</small><div className="cart-page__total"><span>Total</span><strong>{formatPrice(subtotalCents + shippingCents)}</strong></div><Link className="button button--dark button--full" href="/checkout">Continue to checkout <ArrowRight size={16} /></Link><p className="cart-page__note">Secure payment is handled by Stripe Checkout. Card details never touch HUSHWORK.</p></aside></div></main>;
}
