INSERT INTO products (id, slug, name, category, collection, description, price_cents, visual, material, ritual, best_used_when, details, dimensions, care, stock, featured, kind)
VALUES
('prod_low_lamp', 'low-lamp', 'Low Lamp', 'light', 'reset', 'A portable ceramic lamp for the hour when the overhead light has done enough.', 9600, 'lamp', 'Ceramic + warm LED', 'unwind', 'You want the room to soften without going dark.', 'A rechargeable stoneware lamp with a palm-touch cap and six hours of low, warm light per charge.', '14 × 14 × 19 cm', 'Wipe with a dry, soft cloth. Do not submerge.', 24, TRUE, 'product'),
('prod_night_ledger', 'night-ledger', 'Night Ledger', 'write', 'focus', 'An unruled cloth-bound notebook for lists, fragments, and the thought that almost got away.', 1800, 'ledger', 'FSC paper + cotton cloth', 'focus', 'You need a clean surface for the next thought.', 'Sixty-four unruled pages, rounded corners, and a cloth-wrapped spine that gets softer with use.', '12 × 18 cm · 64 pages', 'Keep dry. Recycle when the pages are full.', 72, TRUE, 'product'),
('prod_sunday_cup', 'sunday-cup', 'Sunday Cup', 'table', 'reset', 'Hand-thrown speckled stoneware with a thumb-sized handle and no identical twin.', 4200, 'cup', 'Speckled stoneware', 'host', 'Coffee has become a conversation.', 'Thrown in small batches, glazed by hand, and fired with enough variation to keep the set from feeling like a set.', '9 × 9 × 8 cm · 280 ml', 'Dishwasher and microwave safe.', 36, TRUE, 'product'),
('prod_last_match', 'the-last-match-candle', 'The Last Match Candle', 'light', 'reset', 'Beeswax, cedar, and the small ceremony of striking one more match.', 3400, 'candle', 'Beeswax + smoked glass', 'unwind', 'Dinner is nearly ready and nobody needs to rush.', 'A clean-burning beeswax candle poured in a smoked glass tumbler. The cedar note stays close to the table.', '8 × 8 × 8.5 cm · 180 g', 'Trim the wick to 5 mm before each burn. Never leave unattended.', 48, TRUE, 'product'),
('prod_ashwood_incense', 'ashwood-incense-no-02', 'Ashwood Incense No. 02', 'scent', 'refills', 'Dry pine, black tea, and a trace of smoke for an open window.', 2200, 'incense', 'Pine + black tea', 'unwind', 'The day is still in the walls but no longer in the room.', 'Twenty hand-rolled sticks with a mineral ceramic rest. Light for a minute, then let the room finish the sentence.', '20 sticks · 30 minute burn', 'Burn in a ventilated room on a heat-safe surface.', 40, FALSE, 'product'),
('prod_mending_tin', 'the-mending-tin', 'The Mending Tin', 'carry', 'travel', 'Waxed thread, brass needle, linen patches, and a tiny pair of scissors.', 2900, 'tin', 'Steel + brass + linen', 'repair', 'Something small deserves another year.', 'A pocket-sized repair kit assembled in a hinged steel tin. Useful on a desk, in a drawer, or in the bottom of a bag.', '10 × 7 × 2.5 cm', 'Keep tools dry. Store the thread away from direct sun.', 27, FALSE, 'product'),
('prod_pocket_cloth', 'pocket-cloth', 'Pocket Cloth', 'carry', 'travel', 'A soft cotton square for glasses, cameras, bread, or whatever needs carrying gently.', 1600, 'cloth', 'Washed cotton', 'wander', 'You are leaving with less than you came in with.', 'A 35 cm square of densely woven cotton, finished with a raw edge that improves with every wash.', '35 × 35 cm', 'Machine wash cold. Air dry for the softest finish.', 56, FALSE, 'product'),
('prod_house_matches', 'house-blend-matches', 'House Blend Matches', 'editions', 'gifts', 'Forty oversized matches in a screen-printed drawer box. Striker included.', 1200, 'matches', 'Wood + vegetable ink', 'host', 'A small spark is the whole point.', 'A limited drawer-style box with a full-width striker and extra-long stems for candles and incense.', '11 × 6 × 2 cm · 40 matches', 'Keep dry and away from heat. For adult use only.', 90, FALSE, 'product')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, category = EXCLUDED.category, collection = EXCLUDED.collection,
  description = EXCLUDED.description, price_cents = EXCLUDED.price_cents, visual = EXCLUDED.visual,
  material = EXCLUDED.material, ritual = EXCLUDED.ritual, best_used_when = EXCLUDED.best_used_when,
  details = EXCLUDED.details, dimensions = EXCLUDED.dimensions, care = EXCLUDED.care,
  stock = EXCLUDED.stock, featured = EXCLUDED.featured, kind = EXCLUDED.kind, active = TRUE, updated_at = NOW();

INSERT INTO product_images (id, product_id, url, alt, role, width, height, sort_order)
VALUES
('img_lamp_packshot', 'prod_low_lamp', '/images/products/low-lamp-packshot.webp', 'Warm white ceramic Low Lamp on a cloud studio background', 'packshot', 1200, 1200, 0),
('img_lamp_lifestyle', 'prod_low_lamp', '/images/products/hushwork-reset-room.webp', 'Low Lamp glowing on a pale oak desk beside a notebook and cup', 'lifestyle', 1600, 900, 1),
('img_lamp_detail', 'prod_low_lamp', '/images/products/low-lamp-lifestyle.webp', 'Low Lamp glowing on an oak bedside table at blue hour', 'detail', 1122, 1402, 2),
('img_ledger_packshot', 'prod_night_ledger', '/images/products/night-ledger-packshot.webp', 'Charcoal cloth-bound Night Ledger notebook on a stone plinth', 'packshot', 1200, 1200, 0),
('img_ledger_lifestyle', 'prod_night_ledger', '/images/products/hushwork-reset-room.webp', 'Night Ledger notebook on a lived-in desk beside the Low Lamp', 'lifestyle', 1600, 900, 1),
('img_ledger_detail', 'prod_night_ledger', '/images/products/night-ledger-lifestyle.webp', 'Night Ledger open on a quiet writing desk with a graphite pencil', 'detail', 1122, 1402, 2),
('img_cup_packshot', 'prod_sunday_cup', '/images/products/sunday-cup-packshot.webp', 'Speckled ivory Sunday Cup with a loop handle', 'packshot', 1200, 1200, 0),
('img_cup_lifestyle', 'prod_sunday_cup', '/images/products/hushwork-reset-room.webp', 'Sunday Cup on a pale oak desk in warm window light', 'lifestyle', 1600, 900, 1),
('img_cup_detail', 'prod_sunday_cup', '/images/products/sunday-cup-lifestyle.webp', 'Sunday Cup with coffee on a pale oak breakfast table', 'detail', 1122, 1402, 2),
('img_candle_packshot', 'prod_last_match', '/images/products/last-match-candle-packshot.webp', 'Smoked glass beeswax candle with a warm flame', 'packshot', 1200, 1200, 0),
('img_candle_lifestyle', 'prod_last_match', '/images/products/hushwork-reset-room.webp', 'Candle and ceramic lamp creating a quiet evening desk scene', 'lifestyle', 1600, 900, 1),
('img_candle_detail', 'prod_last_match', '/images/products/last-match-candle-lifestyle.webp', 'Last Match Candle glowing on a dark oak dining table at dusk', 'detail', 1122, 1402, 2),
('img_tin_packshot', 'prod_mending_tin', '/images/products/mending-tin-packshot.webp', 'Open brushed-steel repair kit with linen patches and brass tools', 'packshot', 1200, 1200, 0),
('img_tin_lifestyle', 'prod_mending_tin', '/images/products/hushwork-reset-room.webp', 'Small repair tools arranged beside a cloth notebook', 'lifestyle', 1600, 900, 1),
('img_tin_detail', 'prod_mending_tin', '/images/products/mending-tin-lifestyle.webp', 'Mending Tin open beside a folded cotton shirt on a travel desk', 'detail', 1122, 1402, 2),
('img_incense_packshot', 'prod_ashwood_incense', '/images/products/ashwood-incense-packshot.webp', 'Ashwood incense bundle with a mineral ceramic rest', 'packshot', 1200, 1200, 0),
('img_incense_lifestyle', 'prod_ashwood_incense', '/images/products/hushwork-reset-room.webp', 'Incense rest and warm lamp on a quiet evening surface', 'lifestyle', 1600, 900, 1),
('img_incense_detail', 'prod_ashwood_incense', '/images/products/ashwood-incense-lifestyle.webp', 'Ashwood incense and ceramic rest on a stone table near an open window', 'detail', 1122, 1402, 2),
('img_cloth_packshot', 'prod_pocket_cloth', '/images/products/pocket-cloth-packshot.webp', 'Folded washed cotton Pocket Cloth on a cloud background', 'packshot', 1200, 1200, 0),
('img_cloth_lifestyle', 'prod_pocket_cloth', '/images/products/hushwork-reset-room.webp', 'Pocket Cloth folded on a pale oak desk beside a notebook', 'lifestyle', 1600, 900, 1),
('img_matches_packshot', 'prod_house_matches', '/images/products/house-matches-packshot.webp', 'Drawer box of oversized House Blend Matches', 'packshot', 1200, 1200, 0),
('img_matches_lifestyle', 'prod_house_matches', '/images/products/hushwork-reset-room.webp', 'House Blend Matches beside a candle in a lived-in room', 'lifestyle', 1600, 900, 1)
ON CONFLICT (id) DO UPDATE SET url = EXCLUDED.url, alt = EXCLUDED.alt, role = EXCLUDED.role, width = EXCLUDED.width, height = EXCLUDED.height, sort_order = EXCLUDED.sort_order;
